feature/auth
turchin-aa/Devico_FinalProject_Server pull request #1
Opened 2022-04-27 16:42 UTC by turchin-aa

2022-04-27 16:58 UTC, VolodymyrDevico requested changes

2022-04-27 16:58 UTC, VolodymyrDevico commented on index.ts
> +  const db = new Sequelize('devico_finalproject', 'root', '123456', {
Move to .env

2022-04-27 16:58 UTC, VolodymyrDevico commented on index.ts
> +      console.log('Соединение с БД было успешно установлено')
On english pls

2022-04-27 16:58 UTC, VolodymyrDevico commented on index.ts
> +  const User = db.define("user", {
move to another folder

2022-04-27 16:58 UTC, VolodymyrDevico commented on routes/auth.routes.ts
> +        const {email, password} = req.body
Fix prettier

2022-04-28 21:33 UTC, ntnshpig reviewed
Nice job, but sometimes it is hard to read.

2022-05-04 09:00 UTC, closed without merging