feature/auth/change password
turchin-aa/Devico_FinalProject_Server pull request #2
Opened 2022-05-04 14:07 UTC by turchin-aa

2022-05-04 14:20 UTC, VolodymyrDevico requested changes

2022-05-04 14:20 UTC, VolodymyrDevico commented on controllers/auth.controller.ts
> +    const tokenFromDB = await findToken(refreshToken)
Better use access token for this purposes

2022-05-04 14:20 UTC, VolodymyrDevico commented on controllers/auth.controller.ts
> +    const resetToken: any = generateResetToken({ id, email })
don't use any type

2022-05-04 14:20 UTC, VolodymyrDevico commented on db/database.ts
> +const DB: any = process.env.DB
const { ... } = process.env

2022-05-04 14:20 UTC, VolodymyrDevico commented on dist/index.js
>  };
remove dist

2022-05-05 12:15 UTC, ntnshpig approved these changes

2022-05-06 10:30 UTC, merged